-- ===============================================
-- Urban Air Quality Monitoring System
-- MySQL Database Schema
-- ===============================================

-- Create database if not exists
CREATE DATABASE IF NOT EXISTS air_quality_db
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

USE air_quality_db;

-- ===============================================
-- Table: air_quality
-- Stores air quality readings with all pollutant measurements
-- ===============================================
CREATE TABLE IF NOT EXISTS air_quality (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    aqi INT NOT NULL,
    category VARCHAR(50) NOT NULL,
    health_message VARCHAR(500) NOT NULL,
    pm25 DOUBLE NOT NULL,
    pm10 DOUBLE NOT NULL,
    co DOUBLE NOT NULL,
    no2 DOUBLE NOT NULL,
    o3 DOUBLE NOT NULL,
    temperature DOUBLE NOT NULL,
    humidity DOUBLE NOT NULL,
    recorded_at DATETIME NOT NULL,
    INDEX idx_recorded_at (recorded_at),
    INDEX idx_aqi (aqi)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ===============================================
-- Table: subscribers
-- Stores citizen subscriptions for air quality alerts
-- ===============================================
CREATE TABLE IF NOT EXISTS subscribers (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    threshold INT NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at DATETIME NOT NULL,
    INDEX idx_email (email),
    INDEX idx_threshold (threshold),
    INDEX idx_active (is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ===============================================
-- Table: alert_logs
-- Stores history of alerts sent to subscribers
-- ===============================================
CREATE TABLE IF NOT EXISTS alert_logs (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    subscriber_email VARCHAR(150) NOT NULL,
    subscriber_name VARCHAR(100) NOT NULL,
    threshold INT NOT NULL,
    current_aqi INT NOT NULL,
    category VARCHAR(50) NOT NULL,
    health_message VARCHAR(500) NOT NULL,
    sent_at DATETIME NOT NULL,
    email_sent BOOLEAN DEFAULT FALSE,
    INDEX idx_sent_at (sent_at),
    INDEX idx_subscriber_email (subscriber_email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ===============================================
-- Sample Data (Optional - for initial testing)
-- ===============================================

-- Sample subscriber
INSERT INTO subscribers (name, email, threshold, is_active, created_at)
VALUES 
    ('Test User', 'test@example.com', 150, TRUE, NOW())
ON DUPLICATE KEY UPDATE name=name;

-- Note: Air quality data will be automatically generated by the scheduler
-- No need to insert sample air quality data manually
